site_name: Aegis2FA Documentation
site_description: Production-ready Two-Factor Authentication service with enterprise-grade security
site_author: Ilia01
site_url: https://Ilia01.github.io/Aegis2FA/

repo_name: Ilia01/Aegis2FA
repo_url: https://github.com/Ilia01/Aegis2FA
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode with gradient accent
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode with vibrant accent
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Table of contents
    - toc.follow
    - toc.integrate
    # Content
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/shield-lock
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ilia01/Aegis2FA
      name: View on GitHub
    - icon: fontawesome/solid/bug
      link: https://github.com/Ilia01/Aegis2FA/issues
      name: Report Issues
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yourserver
      name: Join Discord
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by opening an issue.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search:
      lang: en
  - swagger-ui-tag
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Ilia01
      repo: Aegis2FA

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Zero-Budget Deployment: getting-started/zero-budget.md
  - Architecture:
    - Overview: architecture/overview.md
    - Authentication Flow: architecture/authentication-flow.md
    - Database Schema: architecture/database-schema.md
  - API Reference:
    - Interactive API Docs: api/index.md
    - Authentication: api/authentication.md
    - Two-Factor Auth: api/two-factor.md
    - Webhooks: api/webhooks.md
    - API Keys: api/api-keys.md
    - Health Checks: api/health.md
  - Guides:
    - Integration Guide: guides/integration.md
    - TOTP Setup: guides/totp-setup.md
    - SMS 2FA: guides/sms-setup.md
    - Email 2FA: guides/email-setup.md
    - API Keys: guides/api-keys.md
    - Webhooks: guides/webhooks.md
    - Trusted Devices: guides/trusted-devices.md
  - Development:
    - Contributing: development/contributing.md
    - Backend Development: development/backend.md
    - Frontend Development: development/frontend.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
  - Deployment:
    - Docker: deployment/docker.md
    - Cloud Platforms: deployment/cloud-platforms.md
    - SSL Setup: deployment/ssl.md
    - Monitoring: deployment/monitoring.md
  - Reference:
    - Environment Variables: reference/environment-variables.md
    - Configuration: reference/configuration.md
    - Error Codes: reference/error-codes.md
  - FAQ: faq.md
  - Changelog: changelog.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

copyright: Copyright &copy; 2024 Aegis2FA | Built with Material for MkDocs
